# Generated by Django 5.2.5 on 2025-09-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_experience_city_experience_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institute_avatar',
            field=models.ImageField(default='default.jpg', upload_to='institute'),
        ),
        migrations.AddField(
            model_name='experience',
            name='workplace_avatar',
            field=models.ImageField(default='default.jpg', upload_to='workplace'),
        ),
        migrations.AddField(
            model_name='internship',
            name='internship_avatar',
            field=models.ImageField(default='default.jpg', upload_to='internship'),
        ),
    ]
