# Generated by Django 5.2.5 on 2025-09-05 12:12

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmatPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('quant', 'Quant'), ('verbal', 'Verbal'), ('insight', 'Insight'), ('all', 'All')], default='quant', max_length=20)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('Medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed'), ('real', 'Real')], default='real', max_length=20)),
                ('type', models.CharField(choices=[('gmat', 'GMAT'), ('sat', 'SAT'), ('gre', 'GRE'), ('other', 'Other')], default='gmat', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_free', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GmatPracitceQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Question')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pracitce_images/')),
                ('choice1', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Choice 1')),
                ('choice2', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Choice 2')),
                ('choice3', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Choice 3')),
                ('choice4', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Choice 4')),
                ('choice5', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Choice 5')),
                ('correct_answer', models.IntegerField(choices=[(1, 'Choice 1'), (2, 'Choice 2'), (3, 'Choice 3'), (4, 'Choice 4'), (5, 'Choice 5')])),
                ('explanation', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Explanation')),
                ('category', models.CharField(choices=[('quant', 'Quant'), ('verbal', 'Verbal'), ('insight', 'Insight'), ('other', 'Other')], default='quant', max_length=20)),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_questions', to=settings.AUTH_USER_MODEL)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_questions', to='gmat.gmatpractice')),
            ],
        ),
        migrations.CreateModel(
            name='GmatPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmat.gmatpractice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserGmatPracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmat.gmatpracitcequestions')),
                ('test_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt_practice_answers', to='gmat.gmatpracticeattempt')),
                ('test_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_practice_answers', to='gmat.gmatpractice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pr_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
