# Generated by Django 5.2.5 on 2025-09-05 12:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GmatPracitceQuestions',
            new_name='PracitceQuestions',
        ),
        migrations.RenameModel(
            old_name='GmatPractice',
            new_name='Practice',
        ),
        migrations.RenameModel(
            old_name='GmatPracticeAttempt',
            new_name='PracticeAttempt',
        ),
        migrations.RenameModel(
            old_name='UserGmatPracticeAnswer',
            new_name='UserPrAnswer',
        ),
    ]
