# Generated by Django 5.2.5 on 2025-09-15 09:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('given_by', models.CharField(max_length=150)),
                ('given_at', models.DateField(default=django.utils.timezone.now)),
                ('has_deadline', models.BooleanField()),
                ('expire_at', models.DateField(default=django.utils.timezone.now)),
                ('score', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='certificates')),
                ('link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('reading', models.CharField(choices=[('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('medium', 'medium'), ('beginner', 'beginner')], default='intermediate', max_length=150)),
                ('speaking', models.CharField(choices=[('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('medium', 'medium'), ('beginner', 'beginner')], default='intermediate', max_length=150)),
                ('listening', models.CharField(choices=[('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('medium', 'medium'), ('beginner', 'beginner')], default='intermediate', max_length=150)),
                ('writing', models.CharField(choices=[('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('medium', 'medium'), ('beginner', 'beginner')], default='intermediate', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('know_from', models.DateField(default=django.utils.timezone.now)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.certificates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('coding', 'Coding'), ('soft', 'Soft'), ('hard', 'Hard'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('skilled_date', models.DateField(default=django.utils.timezone.now)),
                ('progress', models.CharField(choices=[('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('average', 'Average'), ('beginner', 'Beginner'), ('beginner', 'Beginner')], default='average', max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
